# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Intelligent Systems
email: socia@di.ubi.pt
description: >-
  The Intelligent Systems Laboratory at the University of Beira Interior
  focuses on computer vision, pattern recognition, and biometrics research.
baseurl: "/inlab-ubi" # the subpath of your site, e.g. /blog
url: "https://kailashhambarde.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb # Optional
# github_username:  jekyll # Optional
logo: "/assets/images/lab_logo.png" # Path to your site logo, relative to root

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections configuration
collections:
  team_members:
    output: true # Generate individual pages for each team member
    permalink: /inlab-ubi/team/:path/ # URL structure for member pages (e.g., /inlab-ubi/team/hugo_proenca/)

# Defaults
defaults:
  - scope:
      path: ""
      type: "team_members"
    values:
      layout: "member"
